### ISSUE TITLE
USB Shield to GND

### ISSUE THREAD

**Issue by HarrisonHandley** [ModelRocketryAvionics/Avionics-Board#2]
Need to check if all mounting pads for the USB connector should be connected to GND.

**Comment by Michael-Graves** [comment]
It should

**Comment by HarrisonHandley** [comment]
There's 6 pads for connecting the shield to the PCB. 4 of them have a no trace zone surrounding them. The 2 closest pads to the data pins aren't in that zone and are currently connected to GND.
