### ISSUE TITLE
Jumper Footprints

### ISSUE THREAD

**Issue by HarrisonHandley** [ModelRocketryAvionics/Avionics-Board#3]
The jumper Footprints for both NO and NC need to be done along with selecting the components.

**Comment by Michael-Graves** [comment]
Can just do solder/cut jumpers where you can cut a trace or solder 2 pads together to select the state, won't need any components.

**Comment by HarrisonHandley** [comment]
Should we leave the footprints at 0603 size, and then later you can connect the pads with wire. Or for the NC connections when we assemble the board.

**Comment by Michael-Graves** [comment]
We should make custom footprints for NC and NO. but essentially its just a 0603 footprint with a wire between them and no solder mask
